image: node:22-alpine

stages:
#  - install
#  - test
  - dependabot

variables:
  NODE_OPTIONS: "--max-old-space-size=4096"  # 4GB RAM limit

cache:
  key: ${CI_COMMIT_REF_SLUG}
  policy: pull
  paths: [ .npm ]

#install:
#  stage: install
#  script:
#    - npm ci --prefer-offline --cache .npm --no-audit --progress=false
#  artifacts:
#    paths: [ node_modules ]
#  cache:
#    policy: pull-push
#
#test_unit:
#  stage: test
#  script:
#    - npm run test:unit
#  coverage: /All files[^|]*|[^|]*\s+([\d\.]+)/
#  artifacts:
#    paths: [ coverage ]
#    expire_in: 1 week
#    reports:
#      coverage_report:
#        coverage_format: cobertura
#        path: coverage/cobertura-coverage.xml
#
#test_codestyles:
#  stage: test
#  script:
#    - npm run test:codestyles
#
#test_build:
#  stage: test
#  script:
#    - npm run build
#  artifacts:
#    paths: [ dist ]
#    expire_in: 1 week
#
#test_type:
#  stage: test
#  script:
#    - npm run test:type

dependabot:
  stage: dependabot
  image: node:latest
#  rules:
#    - if: $CI_PIPELINE_SOURCE == "schedule"
  script:
    - npm install -g npm-check-updates
    - ncu -u
    - npm install
    - git config --global user.name "GitLab CI"
    - git config --global user.email "gitlab-ci@example.com"
    - git remote add gitlab_origin https://oauth2:$GITLAB_API_TOKEN@gitlab.com/$CI_PROJECT_PATH.git
    - git checkout -b "update-deps-$(date +%Y%m%d)"
    - git add package.json package-lock.json
    - git commit -m "automatic dependency update"
    - git push gitlab_origin "update-deps-$(date +%Y%m%d)" --force
    - >-
      curl --request POST --header "PRIVATE-TOKEN: $GITLAB_API_TOKEN"
      --form "title=automatic dependency update $(date +%Y-%m-%d)"
      --form "description=automatic dependency update"
      --form "source_branch=update-deps-$(date +%Y%m%d)"
      --form "target_branch=main"
      "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/merge_requests"
